# Generated by Django 3.2.12 on 2022-03-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='max',
            field=models.IntegerField(default=-1),
        ),
    ]
