# Generated by Django 3.2.12 on 2022-03-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='random',
            field=models.IntegerField(default=0),
        ),
    ]
