# Generated by Django 3.2.12 on 2022-03-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220320_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sum',
            field=models.IntegerField(default=0),
        ),
    ]
