# Generated by Django 3.2.12 on 2022-03-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default=6, max_length=25),
        ),
    ]
