# Generated by Django 3.2.12 on 2022-03-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_question_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slug',
        ),
    ]
