# Generated by Django 3.2.12 on 2022-03-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
