# Generated by Django 3.2.12 on 2022-04-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_question_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
